# Site Info
title: Yenarue's DevLog
tagline: 'Beautiful Programming :-)'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: http://yenarue.github.io
logo: ''

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
#paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Yenarue
  description: <strong>제너럴리스트</strong>를 꿈꾸는 안드로이드 개발자, 김예나(Yenarue) 입니다.
  gravatar: c77a29c5315142c8dc84adb4c92e9a18  # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/yena-kim-yenarue/
    github:    https://github.com/yenarue
    facebook:  https://www.facebook.com/yenarue
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    email:     yenarue@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/yenarue/yenarue.github.io'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-118279749-1' # leave blank if you don't want google analytics
disqus_short_name: 'yenarue-dev-blog' # leave blank if you don't want disqus

